services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Bangkok

volumes:
  mysqldata:
    driver: local